#!/bin/bash

SCRIPT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

# Build all Open3D dependencies with conflicting versions in the apt package manager on Ubuntu 20.04.
${SCRIPT_PATH}/build-assimp
${SCRIPT_PATH}/build-eigen
${SCRIPT_PATH}/build-jsoncpp
${SCRIPT_PATH}/build-qhull