#!/bin/bash

SCRIPT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

# Build all Open3D dependencies whose apt version is incorrect.
${SCRIPT_PATH}/build-assimp
${SCRIPT_PATH}/build-eigen
${SCRIPT_PATH}/build-jsoncpp
${SCRIPT_PATH}/build-qhull

# Build Open3D
${SCRIPT_PATH}/build-open3d