#!/bin/bash

SCRIPT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

# Get source, build and install directories and common functions.
source ${SCRIPT_PATH}/common

LAPACKE_NAME=lapacke
LAPACKE_URL=https://github.com/Reference-LAPACK/lapack.git
LAPACKE_BRANCH=v3.12.1
LAPACKE_SOURCE_PATH=${COMMON_SOURCE_PATH}/${LAPACKE_NAME}
LAPACKE_BUILD_PATH=${COMMON_BUILD_PATH}/${LAPACKE_NAME}
LAPACKE_INSTALL_PATH=${COMMON_INSTALL_PATH}/${LAPACKE_NAME}
LAPACKE_FLAGS=(
    -DCMAKE_INSTALL_PREFIX=${LAPACKE_INSTALL_PATH}
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_Fortran_COMPILER=x86_64-w64-mingw32-gfortran
    -DLAPACK_TESTING_USE_PYTHON=OFF
    -DBUILD_TESTING=OFF
    -DCBLAS=ON
    -DUSE_OPTIMIZED_LAPACK=ON
    -DLAPACKE=ON
    # -DBLAS++=ON
    # -DLAPACKE++=ON
    )

# Skip if the library is already installed
FindLibrary ${LAPACKE_INSTALL_PATH} ${LAPACKE_NAME}
if [ $? -ne 0 ]; then
    exit 0
fi

echo ""
echo "*************************************************************"
echo "*                     Build LAPACKE                         *"
echo "*************************************************************"
echo ""

GitClone ${LAPACKE_SOURCE_PATH} ${LAPACKE_URL} ${LAPACKE_BRANCH}
BuildAndInstall ${LAPACKE_SOURCE_PATH} ${LAPACKE_BUILD_PATH} ${LAPACKE_FLAGS[@]}

echo ""
echo "*************************************************************"
echo "*                 Build LAPACKE successful                  *"
echo "*************************************************************"
echo ""
