#!/bin/bash

SCRIPT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

# Get source, build and install directories and common functions.
source ${SCRIPT_PATH}/common

PNG_NAME=png
PNG_URL=https://github.com/pnggroup/libpng.git
PNG_BRANCH=v1.6.46
PNG_SOURCE_PATH=${COMMON_SOURCE_PATH}/${PNG_NAME}
PNG_BUILD_PATH=${COMMON_BUILD_PATH}/${PNG_NAME}
PNG_INSTALL_PATH=${COMMON_INSTALL_PATH}/${PNG_NAME}
PNG_FLAGS=(
    -DCMAKE_INSTALL_PREFIX=${PNG_INSTALL_PATH}
    -DCMAKE_BUILD_TYPE=Release
    -DPNG_SHARED=OFF
    -DPNG_EXECUTABLES=OFF
    -DPNG_TESTS=OFF
    -DZLIB_ROOT=${COMMON_INSTALL_PATH}/zlib)

# Skip if the library is already installed
FindLibrary ${PNG_INSTALL_PATH} PNG
if [ $? -ne 0 ]; then
    exit 0
fi

echo ""
echo "*************************************************************"
echo "*                       Build PNG                           *"
echo "*************************************************************"
echo ""

GitClone ${PNG_SOURCE_PATH} ${PNG_URL} ${PNG_BRANCH}
BuildAndInstall ${PNG_SOURCE_PATH} ${PNG_BUILD_PATH} ${PNG_FLAGS[@]}

echo ""
echo "*************************************************************"
echo "*                   Build PNG successful                    *"
echo "*************************************************************"
echo ""
