#!/bin/bash

SCRIPT_PATH="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

# Get source, build and install directories and common functions.
source ${SCRIPT_PATH}/common

QHULL_NAME=qhull
QHULL_URL=git@github.com:qhull/qhull.git
QHULL_BRANCH=v8.0.2
QHULL_SOURCE_PATH=${COMMON_SOURCE_PATH}/${QHULL_NAME}
QHULL_BUILD_PATH=${COMMON_BUILD_PATH}/${QHULL_NAME}
QHULL_INSTALL_PATH=${COMMON_INSTALL_PATH}/${QHULL_NAME}
QHULL_DEPENDENCIES=""
QHULL_FLAGS=(
    -DCMAKE_INSTALL_PREFIX=${QHULL_INSTALL_PATH}
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_STATIC_LIBS=ON
    -DCMAKE_CXX_FLAGS='-fPIC'
    -DCMAKE_C_FLAGS='-fPIC')

# Skip if the library is already installed
FindLibrary ${QHULL_INSTALL_PATH} QHull
if [ $? -ne 0 ]; then
    exit 0
fi

echo ""
echo "*************************************************************"
echo "*                      Build QHull                          *"
echo "*************************************************************"
echo ""

InstallPackages ${COMMON_REQUIRED_PACKAGES} ${QHULL_DEPENDENCIES}
GitClone ${QHULL_SOURCE_PATH} ${QHULL_URL} ${QHULL_BRANCH}
BuildAndInstall ${QHULL_SOURCE_PATH} ${QHULL_BUILD_PATH} ${QHULL_FLAGS[@]}
ScrubLibraries ${QHULL_INSTALL_PATH}/lib

# The pkgconfig directory contains information about the build machine, and it is not needed.
rm -rf ${QHULL_INSTALL_PATH}/lib/pkgconfig

echo ""
echo "*************************************************************"
echo "*                  Build QHull successful                   *"
echo "*************************************************************"
echo ""